### ISSUE TITLE
A mechanism for replacing parts of the printed strings

### ISSUE THREAD

**Issue by athas** [diku-dk/lys#5]
Sometimes programs can let you dynamically choose between various options, identified with an integer.  It would be nice if these can be represented in the text with a string, rather than just a number.  However, we still don't want to ship strings back from the GPU.  It would be nice if we could somehow return the possible strings once, and then just return an index from `text_content`.  I'm not completely sure how to do this.  Maybe we can extend the format string and encode options directly?

    let text_format = "FPS: %d\nColour: %[red|green|blue]"

**Comment by nqpz** [comment]
I like extending the format string with `%[...]`.  I can't think of a less complicated way that still supports printing strings.

**Comment by athas** [comment]
<img width="400" alt="champ" src="https://user-images.githubusercontent.com/55833/60768935-12c13280-a0ca-11e9-803f-95b335661728.png">
