### ISSUE TITLE
Problems with the demo

### ISSUE THREAD

**Issue by nevrome** [diku-dk/lys#7]
When I run `make` I see

```
cat lib/github.com/diku-dk/lys/genlys.fut | sed 's/"lys"/"lys"/' > lys_wrapper.fut
futhark opencl --library lys_wrapper.fut
Error at lib/github.com/diku-dk/lys/lys.fut:118:1-126:1:
Module type specifies
  val render :
    {h: i64, w: i64} -> [][]u32
but module provides
  val render :
    {h: i32, w: i32} -> *[][]u32
Types
  i64
and
  i32
do not match.
When matching types of record field "h".
When matching parameter types.

If you find this error message confusing, uninformative, or wrong, please open an issue at
https://github.com/diku-dk/futhark/issues.
make: *** [lib/github.com/diku-dk/lys/common.mk:27: lys_wrapper.c] Error 2
rm lys_wrapper.fut
```

I'm on Manjaro Linux 5.4.67-1

**Comment by nqpz** [comment]
Hi @nevrome 

Thanks for the reporting. What version of Futhark are you using? Due to recent breaking changes you will need to use at least Futhark version 0.18.1; see https://futhark-lang.org/blog/2020-10-08-futhark-0.18.1-released.html for more information on this.

**Comment by nevrome** [comment]
Ah - I see. Thank you for the hint! 

I was on the default futhark-bin from AUR, which was 0.16.3. I installed from source now (0.19.0) and got past this error.

It compiles now, but fails at runtime with 

```
(embedded Futhark): lys_wrapper.c:2390: OpenCL call
  clGetPlatformIDs(0, NULL, &num_platforms)
failed with error code -1001 (Unknown)
```

I guess I have to figure out my OpenCL setup next :+1:

**Comment by nevrome** [comment]
Excellent - works now! 

I had to install the necessary [opencl implementation](https://wiki.archlinux.org/index.php/GPGPU), not just the headers.
